---
- hosts: tomcat-servers 
  vars:
  - warName: sample.war
  - warRemotePath: /root/sample/war

  tasks:
  - name: Download WAR to server
    command: wget https://tomcat.apache.org/tomcat-7.0-doc/appdev/sample/sample.war -O {{ warRemotePath }}/{{ warName }}
  
  - name: Unzip WAR file
    unarchive: src={{ warRemotePath }}/{{ warName }} dest=/var/lib/tomcat/webapps/ROOT/ copy=no mode=0755 owner=tomcat group=tomcat
    notify:
        - restart tomcat
   
  - name: Delete remote war file
    file: path={{ warRemotePath }}/{{ warName }} state=absent

  handlers:
    - name: restart tomcat
      service: name=tomcat state=restarted
